### ISSUE TITLE
Feature Request: Add option not to extract Attachment

### ISSUE THREAD

**Issue by Nikostratos** [YujiSoftware/msg2txt#1]
Hey,
thanks for this simple yet effective software.
It is what I had been looking for a while.
Works great and quick.

I want to use this in combination with lf file manager and preview the message contents of .msg files.

I don't have a JAVA compiler at hand.
But it shouldn't be hard, right?

in /src/main/java/org/apache/poi/examples/hsmf/Msg2txt.java
`Boolean extractAttachments; `

line 104
`if (attachments.length > 0 AND extractAttachments) {`

And then we read the 2nd argument of "msg2txt.bat" optionally, so that it can be called:
`msg2txt.bat message.msg true`
`msg2txt.bat message.msg false`

**Comment by YujiSoftware** [comment]
Thank you for great idea!

I implemented this issue in v1.1.0 as `/t` (Windows-style), `-t`, `--text-only` (Linux-style) option.
`msg2txt.bat /t message.msg`

**Comment by YujiSoftware** [comment]
Released v1.1.0👍 
https://github.com/YujiSoftware/msg2txt/releases/tag/1.1.0
