### ISSUE TITLE
Feature Request: Configurable output

### ISSUE THREAD

**Issue by Nikostratos** [YujiSoftware/msg2txt#2]
The msg2txt API extracts the files in the same folder as the *msg file is.

However this is not convenient, e.g. when extracting message, which are on a command server.
Rather I'd extract these in a temporary folder.

e.g.
`msg2txt \\server\mail\message221.msg C:\temp`
would write the txt file (and optionally attachment) to C:\temp.

What do you think?

**Comment by YujiSoftware** [comment]
Thank you for great idea!

I implemented this issue in v1.1.0 as `/o` (Windows-style), `-o`, `--ouput` (Linux-style) option.
`msg2txt.bat /o C:\temp message.msg`
